/**
 * Creates (or replaces) the "Daily Registration Regression" sheet in testData.xlsx — 41 test cases.
 * Run once: node scripts/addDailyRegistrationSheet.js
 */
const XLSX = require("xlsx");
const path = require("path");

const FILE = path.resolve(__dirname, "../src/resources/data/testData.xlsx");
const SHEET_NAME = "Daily Registration Regression";

const rows = [
    // ── DRR: Daily Registration Report — Positive ────────────────────────────
    {
        "Test Case ID": "DRR-001",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Daily Registration Report page loads successfully with all KPI cards, charts and tables displayed.",
        "Test Case Type": "Positive",
        "Preconditions": "User is logged in as Tenant admin",
        "Test Steps": "1. Navigate to BI & Analytics > Daily Registration Report\n2. Verify page heading visible\n3. Verify KPI cards (Total, Customers, Partners, Staff, Verified Rate) visible\n4. Verify trend chart and Registration Detail table visible",
        "Test Data": "URL: /analytics/dailyRegistration",
        "Expected Result": "Page loads with heading, 5 KPI cards, trend chart, and detail table",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-002",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Today filter displays registration data for current day.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click 'Today' filter button\n2. Verify data updates and date range reflects today",
        "Test Data": "Filter: Today",
        "Expected Result": "Today button is active and data shows current day registrations",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-003",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify 7D filter displays registration data for last 7 days.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click '7D' filter button\n2. Verify data updates for last 7 days range",
        "Test Data": "Filter: 7D",
        "Expected Result": "7D button is active and data shows last 7 days registrations",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-004",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify 30D filter displays registration data for last 30 days.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click '30D' filter button\n2. Verify data updates for last 30 days range",
        "Test Data": "Filter: 30D",
        "Expected Result": "30D button is active and data shows last 30 days registrations",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-005",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Custom Date filter displays selected date range data.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click 'Custom' date picker\n2. Select start date and end date\n3. Verify data updates for selected range",
        "Test Data": "Start: 2026-06-01, End: 2026-06-15",
        "Expected Result": "Page shows registrations for the custom date range selected",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-006",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Refresh button reloads latest registration data.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open with data loaded",
        "Test Steps": "1. Click 'Refresh' button\n2. Verify page reloads data without navigation",
        "Test Data": "N/A",
        "Expected Result": "Data refreshes successfully and page remains on report screen",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-007",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Export CSV downloads registration report successfully.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open with data loaded",
        "Test Steps": "1. Click Export CSV button\n2. Verify download initiates\n3. Verify file is not empty",
        "Test Data": "N/A",
        "Expected Result": "CSV file downloads successfully and is not empty",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-008",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify PDF button downloads registration report successfully.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open with data loaded",
        "Test Steps": "1. Click PDF download button\n2. Verify download initiates\n3. Verify file exists and is valid",
        "Test Data": "N/A",
        "Expected Result": "PDF file downloads successfully and is not empty",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-009",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify View Download History navigation works correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click 'View Download History' button\n2. Verify navigation to Download History page",
        "Test Data": "N/A",
        "Expected Result": "User navigates to /analytics/history/CUSTOMER page successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-010",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Schedule Report functionality opens successfully.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click Schedule Report button if present\n2. Verify schedule dialog or page opens",
        "Test Data": "N/A",
        "Expected Result": "Schedule report dialog or page opens without error",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-011",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Customer tab filters registration trend correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click 'Customer' tab in Daily Registration Trend chart\n2. Verify chart updates to show only customer trend data",
        "Test Data": "Tab: Customer",
        "Expected Result": "Trend chart filters to customer data only",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-012",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Partner tab filters registration trend correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click 'Partner' tab in Daily Registration Trend chart\n2. Verify chart updates to show only partner trend data",
        "Test Data": "Tab: Partner",
        "Expected Result": "Trend chart filters to partner data only",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-013",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Staff tab filters registration trend correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click 'Staff' tab in Daily Registration Trend chart\n2. Verify chart updates to show only staff trend data",
        "Test Data": "Tab: Staff",
        "Expected Result": "Trend chart filters to staff data only",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-014",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Registration Details search returns matching records.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open with Registration Detail table visible",
        "Test Steps": "1. Type 'Raj Kumar' in search box and verify matching records\n2. Clear and type 'Priya Singh' and verify\n3. Clear and type 'Amir Khan' and verify",
        "Test Data": "Search: Raj Kumar, Priya Singh, Amir Khan",
        "Expected Result": "Only matching records appear for each search term",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-015",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Role filter displays matching records for Customer, Partner and Staff.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open with Registration Detail table visible",
        "Test Steps": "1. Select 'Customer' from Role dropdown, click Apply, verify results\n2. Select 'Partner' from Role dropdown, click Apply, verify results\n3. Select 'Staff' from Role dropdown, click Apply, verify results",
        "Test Data": "Roles: Customer, Partner, Staff",
        "Expected Result": "Only records matching selected role are displayed",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-016",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify combined Search + Role + Source + Status filtering returns correct results.",
        "Test Case Type": "Positive",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Enter search text, select Role, Source and Status, click Apply\n2. Verify only records matching all conditions appear",
        "Test Data": "Customer+Mobile App+Verified; Customer+Web+Pending; Partner+Social/Ads+Rejected; Staff+Referral+Verified",
        "Expected Result": "Results match all selected filter conditions simultaneously",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── DRR: Daily Registration Report — Negative ────────────────────────────
    {
        "Test Case ID": "DRR-017",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify error when End Date is earlier than Start Date in Custom filter.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Click Custom date picker\n2. Set End Date earlier than Start Date\n3. Verify validation error or no data shown",
        "Test Data": "Start: 2026-06-15, End: 2026-06-01",
        "Expected Result": "Validation error shown or empty result returned for invalid date range",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-018",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify page handles Registration Report API failure gracefully.",
        "Test Case Type": "Negative",
        "Preconditions": "Network is intercepted to simulate API failure",
        "Test Steps": "1. Intercept API call to registration report endpoint\n2. Return 500 error\n3. Verify page shows error state gracefully without crashing",
        "Test Data": "N/A",
        "Expected Result": "Page shows error message or empty state, does not crash",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-019",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify KPI cards display default values when no data exists.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report open with empty dataset",
        "Test Steps": "1. Select a date range with no registrations\n2. Verify KPI cards show 0 or default state",
        "Test Data": "Future date range with no data",
        "Expected Result": "KPI cards display 0 or N/A gracefully without errors",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-020",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify charts display empty state when dataset is unavailable.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report open with empty dataset",
        "Test Steps": "1. Select a date range with no data\n2. Verify trend charts show empty state message",
        "Test Data": "Future date with no data",
        "Expected Result": "Charts show empty state or no-data message, not broken UI",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-021",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Export CSV behavior when no records exist.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report open showing no records",
        "Test Steps": "1. Ensure no records visible in table\n2. Click Export CSV\n3. Verify behavior (error message or empty file)",
        "Test Data": "N/A",
        "Expected Result": "Error message shown or empty CSV with headers only downloaded",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-022",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify PDF export behavior when no records exist.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report open showing no records",
        "Test Steps": "1. Ensure no records visible in table\n2. Click PDF button\n3. Verify behavior (error message or empty file)",
        "Test Data": "N/A",
        "Expected Result": "Error message shown or empty PDF downloaded without crash",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-023",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify Refresh button during network failure handles error gracefully.",
        "Test Case Type": "Negative",
        "Preconditions": "Network is intercepted to simulate failure",
        "Test Steps": "1. Intercept network\n2. Click Refresh button\n3. Verify page shows error or retains previous state gracefully",
        "Test Data": "N/A",
        "Expected Result": "Page does not crash and shows appropriate error state",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-024",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify unauthorized user cannot access Daily Registration Report page.",
        "Test Case Type": "Negative",
        "Preconditions": "User is not logged in or logged in as non-admin role",
        "Test Steps": "1. Navigate directly to /analytics/dailyRegistration without auth\n2. Verify redirect to login or access denied shown",
        "Test Data": "URL: /analytics/dailyRegistration",
        "Expected Result": "User is redirected to login or shown access denied message",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-025",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify random invalid search text returns no records.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report page is open with Registration Detail table visible",
        "Test Steps": "1. Type '@@@@@' in search box, click Apply, verify empty state\n2. Type '123456789' in search box, verify empty state\n3. Type 'xyz_invalid_test', verify empty state",
        "Test Data": "@@@@@, 123456789, xyz_invalid_test",
        "Expected Result": "No records found / empty state shown for each invalid search",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-026",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify filters returning no matching data show empty state in table.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Select a Role+Source+Status combination that has no matching data\n2. Click Apply\n3. Verify empty state message shown",
        "Test Data": "Combination with no matches",
        "Expected Result": "Table shows empty state message, not broken layout",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-027",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify table handles null or missing values correctly without UI crash.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report page is open",
        "Test Steps": "1. Load Registration Detail table\n2. Verify null or empty cells render as dash or empty, not as errors",
        "Test Data": "N/A",
        "Expected Result": "Null/missing values shown as '-' or blank without crashing UI",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-028",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify pagination is hidden or disabled when no records are present.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report open showing no records",
        "Test Steps": "1. Apply filters so no records appear\n2. Verify pagination controls are hidden or disabled",
        "Test Data": "N/A",
        "Expected Result": "Pagination hidden/disabled when table has no records",
        "Priority": "Low",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-029",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify rapid multiple CSV clicks do not create duplicate downloads.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report page is open with data",
        "Test Steps": "1. Click Export CSV button rapidly 5 times\n2. Verify only one download is initiated",
        "Test Data": "5 rapid clicks",
        "Expected Result": "Only one valid CSV download is generated",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-030",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify rapid multiple PDF clicks do not create duplicate files.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report page is open with data",
        "Test Steps": "1. Click PDF button rapidly 5 times\n2. Verify only one download is initiated",
        "Test Data": "5 rapid clicks",
        "Expected Result": "Only one valid PDF download is generated",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "DRR-031",
        "Module": "BI & Analytics",
        "Screen Name": "Daily Registration Report",
        "Test Scenario": "Verify page performance with large registration dataset meets acceptable thresholds.",
        "Test Case Type": "Negative",
        "Preconditions": "Daily Registration Report page open with large dataset",
        "Test Steps": "1. Record page load time\n2. Apply filter and record response time\n3. Perform search and record time\n4. Click export and record time",
        "Test Data": "30D filter (largest dataset period)",
        "Expected Result": "Page load < 5s, filter response < 3s, search response < 2s, export < 10s",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── CDH: Customer Download History — Positive ────────────────────────────
    {
        "Test Case ID": "CDH-001",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify Customer Download History page loads successfully with all sections visible.",
        "Test Case Type": "Positive",
        "Preconditions": "User is logged in as Tenant admin",
        "Test Steps": "1. Navigate to BI & Analytics > Daily Registration Report\n2. Click 'View Download History'\n3. Verify Download History page heading visible",
        "Test Data": "URL: /analytics/history/CUSTOMER",
        "Expected Result": "Download History page loads with heading, filter, table and action buttons",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "CDH-002",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify Today filter works correctly on Download History page.",
        "Test Case Type": "Positive",
        "Preconditions": "Customer Download History page is open",
        "Test Steps": "1. Select 'Today' from the date filter dropdown\n2. Verify table updates to show today's download requests",
        "Test Data": "Filter: Today",
        "Expected Result": "Table refreshes showing download requests from today",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "CDH-003",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify View Customer Report button navigates back to Customer Report correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Customer Download History page is open",
        "Test Steps": "1. Click 'VIEW CUSTOMER REPORT' button\n2. Verify navigation to Daily Registration Report page",
        "Test Data": "N/A",
        "Expected Result": "User navigates to Daily Registration Report page successfully",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "CDH-004",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify Request Downloads table displays all required column headers correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Customer Download History page is open",
        "Test Steps": "1. Verify table column headers: REQUEST#, REQUEST DATE, REQUEST TYPE, REQUESTED BY, STATUS, ACTION",
        "Test Data": "Columns: REQUEST#, REQUEST DATE, REQUEST TYPE, REQUESTED BY, STATUS, ACTION",
        "Expected Result": "All 6 column headers are visible and correctly labeled",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "CDH-005",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify pagination works correctly on Download History page when records exist.",
        "Test Case Type": "Positive",
        "Preconditions": "Customer Download History page has multiple pages of records",
        "Test Steps": "1. Verify pagination controls visible\n2. Click Next page and verify next records load\n3. Click Previous and verify navigation works",
        "Test Data": "N/A",
        "Expected Result": "Pagination navigates between pages correctly",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── CDH: Customer Download History — Negative ────────────────────────────
    {
        "Test Case ID": "CDH-006",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify No Data Available message is displayed when no download records exist.",
        "Test Case Type": "Negative",
        "Preconditions": "Customer Download History page is open with no download records",
        "Test Steps": "1. Verify table shows 'No data available' message\n2. Verify no action buttons are present",
        "Test Data": "N/A",
        "Expected Result": "Table shows 'No data available' message clearly",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "CDH-007",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify Download History page handles API failure gracefully.",
        "Test Case Type": "Negative",
        "Preconditions": "Network is intercepted to simulate API failure",
        "Test Steps": "1. Intercept download history API call\n2. Return 500 error\n3. Verify page shows error state without crashing",
        "Test Data": "N/A",
        "Expected Result": "Page shows error message or empty state gracefully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "CDH-008",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify invalid date filter does not return incorrect download history data.",
        "Test Case Type": "Negative",
        "Preconditions": "Customer Download History page is open",
        "Test Steps": "1. Select an invalid or future date from filter\n2. Verify no incorrect records are returned",
        "Test Data": "Future date with no records",
        "Expected Result": "Empty state shown or validation error — no incorrect data returned",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "CDH-009",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify unauthorized users cannot access Download History page directly.",
        "Test Case Type": "Negative",
        "Preconditions": "User is not logged in",
        "Test Steps": "1. Navigate directly to /analytics/history/CUSTOMER without authentication\n2. Verify redirect to login or access denied",
        "Test Data": "URL: /analytics/history/CUSTOMER",
        "Expected Result": "User redirected to login page or access denied message shown",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    {
        "Test Case ID": "CDH-010",
        "Module": "BI & Analytics",
        "Screen Name": "Customer Download History",
        "Test Scenario": "Verify Action buttons are disabled or absent when download file is unavailable.",
        "Test Case Type": "Negative",
        "Preconditions": "Customer Download History page is open with a failed download request",
        "Test Steps": "1. Identify a record with failed/unavailable file\n2. Verify action button (download) is disabled or absent",
        "Test Data": "N/A",
        "Expected Result": "Download action button is disabled or not shown for unavailable files",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
];

const headers = [
    "Test Case ID",
    "Module",
    "Screen Name",
    "Test Scenario",
    "Test Case Type",
    "Preconditions",
    "Test Steps",
    "Test Data",
    "Expected Result",
    "Priority",
    "Status",
    "Actual Result",
    "Screenshot Path",
    "Execution Time",
];

const wsData = [
    headers,
    ...rows.map((r) => headers.map((h) => r[h] || "")),
];

const wb = XLSX.readFile(FILE);
const ws = XLSX.utils.aoa_to_sheet(wsData);

if (wb.SheetNames.includes(SHEET_NAME)) {
    const idx = wb.SheetNames.indexOf(SHEET_NAME);
    wb.SheetNames.splice(idx, 1);
    delete wb.Sheets[SHEET_NAME];
}
XLSX.utils.book_append_sheet(wb, ws, SHEET_NAME);
XLSX.writeFile(wb, FILE);
console.log(`Written ${rows.length} rows to '${SHEET_NAME}' sheet in ${FILE}`);
