/**
 * Creates (or replaces) the "FAQ (Tenant)" sheet in testData.xlsx — 40 test cases.
 * Run once: node scripts/addFAQSheet.js
 */
const XLSX = require("xlsx");
const path = require("path");

const FILE = path.resolve(__dirname, "../src/resources/data/testData.xlsx");
const SHEET_NAME = "FAQ (Tenant)";

const rows = [
    {
        "Test Case ID": "TC_FAQ_01",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify FAQ Master Config page loads via Setup sidebar navigation",
        "Test Case Type": "Positive",
        "Preconditions": "User is logged in as Tenant admin",
        "Test Steps": "1. Navigate to Home page\n2. Expand Setup menu in sidebar\n3. Click FAQ\n4. Verify page loads successfully",
        "Test Data": "URL: /setup/faq",
        "Expected Result": "FAQ Master Config page heading is visible",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_02",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Dashboard statistics display numeric values",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Master Config page is loaded",
        "Test Steps": "1. Inspect dashboard cards (Total FAQs, Partner FAQs, Customer FAQs, With Media)\n2. Verify the displayed count is a numeric value",
        "Test Data": "N/A",
        "Expected Result": "All dashboard statistic values are numeric",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_03",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify All expected grid columns are displayed",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Master Config page is loaded",
        "Test Steps": "1. Verify presence of table headers: SCOPE, CATEGORY, TOPIC, MEDIA, VIEWS, UPDATED, ACTIONS",
        "Test Data": "N/A",
        "Expected Result": "All expected column headings are displayed correctly in the grid",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_04",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Search by valid topic returns matching FAQ",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Master Config page is loaded and FAQs exist",
        "Test Steps": "1. Enter a valid FAQ topic in the search bar\n2. Verify search returns the matching row",
        "Test Data": "Topic name",
        "Expected Result": "The matching FAQ topic is shown in the grid",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_05",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Partner scope filter shows only Partner FAQs",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Master Config page is loaded",
        "Test Steps": "1. Click on the Partner scope filter tab\n2. Verify all rows displayed have SCOPE value set to PARTNER",
        "Test Data": "Tab: Partner",
        "Expected Result": "Grid only displays FAQs with Partner scope",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_06",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Customer scope filter shows only Customer FAQs",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Master Config page is loaded",
        "Test Steps": "1. Click on the Customer scope filter tab\n2. Verify all rows displayed have SCOPE value set to CUSTOMER",
        "Test Data": "Tab: Customer",
        "Expected Result": "Grid only displays FAQs with Customer scope",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_07",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Staff scope filter tab is clickable and filters table",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Master Config page is loaded",
        "Test Steps": "1. Click on the Staff scope filter tab\n2. Verify grid filters correctly according to Staff scope",
        "Test Data": "Tab: Staff",
        "Expected Result": "Grid only displays FAQs with Staff scope",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_08",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Order category filter filters the FAQ table",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Master Config page is loaded",
        "Test Steps": "1. Click Category filter dropdown\n2. Select Order\n3. Verify grid filters to show Order category FAQs",
        "Test Data": "Category: Order",
        "Expected Result": "Grid displays FAQs of Order category",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_09",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Payment category filter filters the FAQ table",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Master Config page is loaded",
        "Test Steps": "1. Click Category filter dropdown\n2. Select Payment\n3. Verify grid filters to show Payment category FAQs",
        "Test Data": "Category: Payment",
        "Expected Result": "Grid displays FAQs of Payment category",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_10",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Create FAQ button navigates to Create FAQ page",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Master Config page is loaded",
        "Test Steps": "1. Click Create FAQ button\n2. Verify the URL is redirected to the Create FAQ form page",
        "Test Data": "N/A",
        "Expected Result": "Create FAQ form page is displayed successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_11",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Create FAQ with Partner scope, Order category, Media None",
        "Test Case Type": "Positive",
        "Preconditions": "Create FAQ page is loaded",
        "Test Steps": "1. Select Scope: Partner\n2. Select Category: Order\n3. Enter Topic and Description\n4. Select Media Type: None\n5. Click Save FAQ\n6. Verify success toast and FAQ visibility in grid",
        "Test Data": "Scope: Partner, Category: Order, Media: None",
        "Expected Result": "FAQ is created successfully and visible in grid",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_12",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Live Preview updates dynamically as topic is typed",
        "Test Case Type": "Positive",
        "Preconditions": "Create FAQ page is loaded",
        "Test Steps": "1. Enter Scope and Category\n2. Type Topic in input field\n3. Verify Live Preview card matches input details",
        "Test Data": "Scope, Category, Topic",
        "Expected Result": "Live Preview details update instantly as the user types",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_13",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Cancel button on Create FAQ returns to listing page",
        "Test Case Type": "Positive",
        "Preconditions": "Create FAQ page is loaded",
        "Test Steps": "1. Click Cancel button on Create FAQ form\n2. Verify redirection back to FAQ listing page",
        "Test Data": "N/A",
        "Expected Result": "Redirection back to the FAQ listing page is successful",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_14",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Create FAQ with Customer scope",
        "Test Case Type": "Positive",
        "Preconditions": "Create FAQ page is loaded",
        "Test Steps": "1. Select Scope: Customer\n2. Select Category: Payment\n3. Enter Topic and Description\n4. Save and verify creation",
        "Test Data": "Scope: Customer, Category: Payment",
        "Expected Result": "Customer FAQ is created successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_15",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Create FAQ with Staff scope",
        "Test Case Type": "Positive",
        "Preconditions": "Create FAQ page is loaded",
        "Test Steps": "1. Select Scope: Staff\n2. Select Category: Order\n3. Enter Topic and Description\n4. Click Save and verify either success toast or graceful permissions error toast",
        "Test Data": "Scope: Staff, Category: Order",
        "Expected Result": "Creation is processed successfully or rejected gracefully by backend API",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_16",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Sort Order accepts valid numeric value",
        "Test Case Type": "Positive",
        "Preconditions": "Create FAQ page is loaded",
        "Test Steps": "1. Enter numeric value in Sort Order field\n2. Save FAQ and verify no validation errors on sort order",
        "Test Data": "Sort Order: 10",
        "Expected Result": "Sort order accepts numeric values",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_17",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify FAQ Details page loads and shows correct content",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ listing is loaded",
        "Test Steps": "1. Search for FAQ\n2. Click View icon\n3. Verify FAQ details card displays correct category, scope, and description",
        "Test Data": "FAQ Topic",
        "Expected Result": "FAQ Details page loads showing correct values",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_18",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Back button on Details page navigates to listing",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ Details page is loaded",
        "Test Steps": "1. Click Back button\n2. Verify page navigates back to FAQ listing grid",
        "Test Data": "N/A",
        "Expected Result": "Returns to grid list page successfully",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_19",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Topic update persists after save",
        "Test Case Type": "Positive",
        "Preconditions": "Edit FAQ page is loaded",
        "Test Steps": "1. Update FAQ Topic field\n2. Click Save FAQ\n3. Search and view the FAQ topic to check persistence",
        "Test Data": "Updated FAQ Topic",
        "Expected Result": "Updated topic is saved and displays in grid",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_20",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Description update persists after save",
        "Test Case Type": "Positive",
        "Preconditions": "Edit FAQ page is loaded",
        "Test Steps": "1. Update FAQ Description field\n2. Click Save FAQ\n3. Verify description change is displayed in details view",
        "Test Data": "Updated FAQ Description",
        "Expected Result": "Updated description is saved successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_21",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Scope update persists after save",
        "Test Case Type": "Positive",
        "Preconditions": "Edit FAQ page is loaded",
        "Test Steps": "1. Update FAQ Scope value\n2. Click Save FAQ\n3. Verify scope update in grid",
        "Test Data": "Updated Scope value",
        "Expected Result": "Updated scope is saved successfully",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_22",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Edit form accepts category change and save is confirmed",
        "Test Case Type": "Positive",
        "Preconditions": "Edit FAQ page is loaded",
        "Test Steps": "1. Select a new Category from the dropdown\n2. Click Save FAQ\n3. Verify updated category on listing page",
        "Test Data": "Updated Category",
        "Expected Result": "Updated category is saved successfully",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_23",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Sort Order update is accepted and save returns success",
        "Test Case Type": "Positive",
        "Preconditions": "Edit FAQ page is loaded",
        "Test Steps": "1. Update Sort Order field value\n2. Click Save FAQ\n3. Verify success message displayed",
        "Test Data": "Updated Sort Order: 20",
        "Expected Result": "Sort order updates successfully",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_24",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Data persists after browser reload and fresh navigation",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ created and saved",
        "Test Steps": "1. Reload browser window\n2. Navigate back to FAQ listing\n3. Search for FAQ topic\n4. Verify details remain intact",
        "Test Data": "FAQ Topic",
        "Expected Result": "Created FAQ data persists across page reloads and restarts",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_25",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Delete confirmation popup opens on Delete icon click",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ listing is loaded",
        "Test Steps": "1. Search FAQ\n2. Click Delete icon\n3. Verify confirmation popup appears",
        "Test Data": "N/A",
        "Expected Result": "Delete confirmation popup is displayed successfully",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_26",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Cancelling delete keeps the FAQ in the listing",
        "Test Case Type": "Positive",
        "Preconditions": "Delete confirmation popup is open",
        "Test Steps": "1. Click Cancel/No in confirmation popup\n2. Verify the FAQ topic is still present in listing",
        "Test Data": "N/A",
        "Expected Result": "Redirection closes popup, and FAQ remains in the grid",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_27",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Deleting an FAQ removes it from the grid",
        "Test Case Type": "Positive",
        "Preconditions": "Delete confirmation popup is open",
        "Test Steps": "1. Click Yes, delete it!\n2. Verify success toast message\n3. Verify FAQ is no longer visible in grid",
        "Test Data": "N/A",
        "Expected Result": "FAQ is deleted successfully and removed from grid list",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_28",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Dashboard count does not increase after deletion",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ listing is loaded",
        "Test Steps": "1. Note down Total FAQs count\n2. Create a temporary FAQ and verify count increases\n3. Delete the temporary FAQ\n4. Verify count goes back to initial state",
        "Test Data": "N/A",
        "Expected Result": "Dashboard count decreases when FAQ is deleted, reflecting correct totals",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_29",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Search for non-existing FAQ shows no-records state",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ listing is loaded",
        "Test Steps": "1. Enter a non-existing topic in the search bar\n2. Verify grid is empty and displays 'No Records Found'",
        "Test Data": "Search query: NO_FAQ_MATCH_!@#_999999",
        "Expected Result": "Grid displays empty state fallback",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_30",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Search with special characters does not crash the app",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ listing is loaded",
        "Test Steps": "1. Enter special characters in search box\n2. Verify the application handles the query gracefully without breaking the grid",
        "Test Data": "Search query: !@#$%^&*",
        "Expected Result": "Page remains stable and displays empty search state",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_31",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Leaving Topic blank shows validation error",
        "Test Case Type": "Negative",
        "Preconditions": "Create FAQ form page is open",
        "Test Steps": "1. Leave Topic input empty\n2. Click Save FAQ\n3. Verify topic required validation message is shown",
        "Test Data": "N/A",
        "Expected Result": "Topic is required validation message is displayed",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_32",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Leaving Description blank shows validation error",
        "Test Case Type": "Negative",
        "Preconditions": "Create FAQ form page is open",
        "Test Steps": "1. Leave Description text area empty\n2. Click Save FAQ\n3. Verify description required validation message is shown",
        "Test Data": "N/A",
        "Expected Result": "Description is required validation message is displayed",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_33",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Attempting to save without Scope shows validation error",
        "Test Case Type": "Negative",
        "Preconditions": "Create FAQ form page is open",
        "Test Steps": "1. Do not select Scope dropdown\n2. Click Save FAQ\n3. Verify scope required validation message is shown",
        "Test Data": "N/A",
        "Expected Result": "Scope is required validation message is displayed",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_34",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Attempting to save without Category shows validation error",
        "Test Case Type": "Negative",
        "Preconditions": "Create FAQ form page is open",
        "Test Steps": "1. Do not select Category dropdown\n2. Click Save FAQ\n3. Verify category required validation message is shown",
        "Test Data": "N/A",
        "Expected Result": "Category is required validation message is displayed",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_35",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Sort Order rejects alphabetic input",
        "Test Case Type": "Negative",
        "Preconditions": "Create FAQ form page is open",
        "Test Steps": "1. Enter letters in Sort Order field\n2. Verify the field either blocks letters or shows a validation error",
        "Test Data": "Sort Order: ABC",
        "Expected Result": "Sort order accepts only positive integers and blocks letters",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_36",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Sort Order rejects special character input",
        "Test Case Type": "Negative",
        "Preconditions": "Create FAQ form page is open",
        "Test Steps": "1. Enter special characters in Sort Order field\n2. Verify the field either blocks special characters or shows a validation error",
        "Test Data": "Sort Order: #$%",
        "Expected Result": "Sort order accepts only positive integers and blocks special characters",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_37",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Very long Topic text does not break the UI",
        "Test Case Type": "Negative",
        "Preconditions": "Create FAQ form page is open",
        "Test Steps": "1. Input topic of 500 characters\n2. Verify form layouts do not crash or overlap in UI",
        "Test Data": "500 characters Topic",
        "Expected Result": "UI remains stable and handles long values correctly",
        "Priority": "Low",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_38",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Category with no FAQs shows empty state",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ listing is loaded",
        "Test Steps": "1. Select Category with no items\n2. Verify grid displays 'No Records Found' and row count is 0",
        "Test Data": "N/A",
        "Expected Result": "Grid displays empty state message successfully",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_39",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Invalid FAQ URL is handled gracefully without crash",
        "Test Case Type": "Negative",
        "Preconditions": "User is logged in",
        "Test Steps": "1. Navigate directly to an invalid subpage URL under FAQ\n2. Verify page handles it gracefully or redirects to setup/faq",
        "Test Data": "URL: setup/faq/invalid_route_999",
        "Expected Result": "App displays fallback page or redirects gracefully without system crash",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    },
    {
        "Test Case ID": "TC_FAQ_40",
        "Module": "Setup",
        "Screen Name": "FAQ",
        "Test Scenario": "Verify Rapid delete confirmations result in only one delete",
        "Test Case Type": "Positive",
        "Preconditions": "FAQ topic is created and delete popup is open",
        "Test Steps": "1. Click Yes, delete it! confirmation button multiple times in rapid succession\n2. Verify only a single API request is successfully processed and item is deleted exactly once",
        "Test Data": "N/A",
        "Expected Result": "FAQ is deleted successfully and grid remains stable without double-delete error",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Execution Time": "",
        "Screenshot Path": ""
    }
];

const headers = [
    "Test Case ID", "Module", "Screen Name", "Test Scenario", "Test Case Type", 
    "Preconditions", "Test Steps", "Test Data", "Expected Result", "Priority", 
    "Status", "Actual Result", "Execution Time", "Screenshot Path"
];

const wsData = [
    headers,
    ...rows.map((r) => headers.map((h) => r[h] || "")),
];

const wb = XLSX.readFile(FILE);
const ws = XLSX.utils.aoa_to_sheet(wsData);

if (wb.SheetNames.includes(SHEET_NAME)) {
    const idx = wb.SheetNames.indexOf(SHEET_NAME);
    wb.SheetNames.splice(idx, 1);
    delete wb.Sheets[SHEET_NAME];
}
XLSX.utils.book_append_sheet(wb, ws, SHEET_NAME);
XLSX.writeFile(wb, FILE);
console.log(`Written ${rows.length} rows to '${SHEET_NAME}' sheet in ${FILE}`);
