/**
 * Updates (or replaces) the "ItemTest" sheet in testData.xlsx — 78 test cases.
 * Run once: node scripts/addItemTestSheet.js
 */
const XLSX = require("xlsx");
const path = require("path");

const FILE = path.resolve(__dirname, "../src/resources/data/testData.xlsx");
const SHEET_NAME = "ItemTest";

const rows = [
    // ── Item Listing Screen: Positive (TC01 to TC10) ──
    {
        "TestID": "TC01_List_PageLoads",
        "Issue": "29001",
        "Description": "Verify item list loads successfully with selected Market, Category, and Product Catalog filters.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Grid displays corresponding items successfully.",
        "Market": "Market A", "Category": "Category A", "ProductCatalog": "Catalog A", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC02_List_SearchExistingItem",
        "Issue": "29002",
        "Description": "Verify user can search an existing item by name and matching records are displayed.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Grid displays matched product by name.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "TestItem",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC03_List_FilterByMarket",
        "Issue": "29003",
        "Description": "Verify user can filter items by Market and view corresponding results.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Grid records filter correctly by selected Market.",
        "Market": "Market A", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC04_List_FilterByCategory",
        "Issue": "29004",
        "Description": "Verify user can filter items by Category and view corresponding results.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Grid records filter correctly by Category.",
        "Market": "", "Category": "Category A", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC05_List_FilterByProductCatalog",
        "Issue": "29005",
        "Description": "Verify user can filter items by Product Catalog and view corresponding results.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Grid records filter correctly by Catalog.",
        "Market": "", "Category": "", "ProductCatalog": "Catalog A", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC06_List_ClearFilters",
        "Issue": "29006",
        "Description": "Verify user can clear all applied filters using the Clear Filter button.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Filters reset and full listing loads successfully.",
        "Market": "Market A", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC07_List_NavigateCreate",
        "Issue": "29007",
        "Description": "Verify user can navigate to the Create Item page by clicking the Create button.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Create page screen opens successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC08_List_NavigateBulkCreate",
        "Issue": "29008",
        "Description": "Verify user can navigate to the Bulk Create page by clicking the Bulk Create button.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Bulk create page file upload section loaded successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC09_List_ViewItemDetails",
        "Issue": "29009",
        "Description": "Verify user can open item details by clicking the View icon.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Item details screen opens successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC10_List_ToggleStatus",
        "Issue": "29010",
        "Description": "Verify user can enable/disable an item successfully using the status toggle switch.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Status toggles successfully; success toast displays.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },

    // ── Item Listing Screen: Negative (TC11 to TC20) ──
    {
        "TestID": "TC11_List_SearchNonExisting",
        "Issue": "29011",
        "Description": "Verify \"No Records Found\" message is displayed when searching for a non-existing item.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "No Records Found displays in table.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "NONEXISTENT_ITEM_XYZ_999",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC12_List_SearchSpecialChars",
        "Issue": "29012",
        "Description": "Verify system handles special characters entered in the search box without crashing.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Search handles special characters safely.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "!@#$%^",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC13_List_InvalidFilterCombo",
        "Issue": "29013",
        "Description": "Verify item list remains unchanged when an invalid filter combination returns no data.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Table remains empty or retains original state safely.",
        "Market": "InvalidMarket", "Category": "InvalidCategory", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC14_List_UnauthorizedCreate",
        "Issue": "29014",
        "Description": "Verify user cannot access Create Item functionality without required permissions.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Creation buttons are disabled or hidden.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC15_List_UnauthorizedEdit",
        "Issue": "29015",
        "Description": "Verify user cannot access Edit Item functionality without required permissions.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Edit icons are disabled or hidden.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC16_List_UnauthorizedDelete",
        "Issue": "29016",
        "Description": "Verify user cannot delete an item without required permissions.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Delete icons are disabled or hidden.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC17_List_ToggleAPIError",
        "Issue": "29017",
        "Description": "Verify system displays an error message when item status toggle API request fails.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Toggle resets and API failure toast is displayed.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC18_List_BlankSearch",
        "Issue": "29018",
        "Description": "Verify search results are not displayed for blank or whitespace-only search input.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Full listing remains unchanged.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "   ",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC19_List_APITimeout",
        "Issue": "29019",
        "Description": "Verify system handles API timeout/error gracefully while loading item data.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Graceful toaster failure alert displays.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC20_List_RefreshUnavailable",
        "Issue": "29020",
        "Description": "Verify refresh button does not break the page when backend service is unavailable.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Toaster connection error displays; table data remains stable.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },

    // ── View Item Details Screen: Positive (TC21 to TC30) ──
    {
        "TestID": "TC21_View_PageLoads",
        "Issue": "29021",
        "Description": "Verify item details page loads successfully with all saved product information displayed correctly.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Details load correctly in form sections.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC22_View_OrgDetails",
        "Issue": "29022",
        "Description": "Verify Organization details (Market, Category, Catalog, Store) are displayed correctly for the selected item.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Organization profile fields load correct values.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC23_View_PricingSection",
        "Issue": "29023",
        "Description": "Verify Pricing section displays correct Quantity, Price, Discount, and Deal Price values.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Pricing section numeric values show correct formats.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC24_View_ProductTypeFields",
        "Issue": "29024",
        "Description": "Verify Product Type and Type fields display the saved values correctly.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Product type fields load exact configurations.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC25_View_InventoryDetails",
        "Issue": "29025",
        "Description": "Verify Inventory details (Inventory Type and Stock Count) are displayed correctly.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Inventory details load correct stock metrics.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC26_View_MediaFiles",
        "Issue": "29026",
        "Description": "Verify uploaded media files (Icon, Thumbnail, Main Photo) are displayed successfully.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Media preview images load cleanly.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC27_View_AddressSection",
        "Issue": "29027",
        "Description": "Verify Address section displays correct Search Address, City, State, Country, Latitude, and Longitude.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Address profile details display correctly.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC28_View_AvailabilityStatus",
        "Issue": "29028",
        "Description": "Verify Availability status is displayed correctly for the item.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Availability details show exact state.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC29_View_TaxCodeBrand",
        "Issue": "29029",
        "Description": "Verify Tax Code and Brand information are displayed correctly.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Tax code and Brand labels match database configurations.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC30_View_BackButton",
        "Issue": "29030",
        "Description": "Verify Back button navigates the user to the Item List page successfully.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Navigates back to the main listing grid.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },

    // ── View Item Details Screen: Negative (TC31 to TC40) ──
    {
        "TestID": "TC31_View_MissingMandatoryDetail",
        "Issue": "29031",
        "Description": "Verify system displays appropriate placeholder or empty value when a mandatory item detail is missing.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Dash placeholder displays cleanly.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC32_View_MissingMediaFiles",
        "Issue": "29032",
        "Description": "Verify page handles missing media files without breaking the UI.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Fallback placeholder images render safely.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC33_View_InvalidImageURLs",
        "Issue": "29033",
        "Description": "Verify invalid image URLs do not crash the item details page.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Image alt text displays cleanly; no crash triggers.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC34_View_NullOrgDetails",
        "Issue": "29034",
        "Description": "Verify system handles null Organization details gracefully.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Placeholder blanks load cleanly.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC35_View_MissingDealPriceData",
        "Issue": "29035",
        "Description": "Verify Deal Price is not displayed incorrectly when discount calculation data is missing.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Deal Price defaults to base Price.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC36_View_InvalidLatLong",
        "Issue": "29036",
        "Description": "Verify invalid Latitude/Longitude values are handled without UI errors.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Empty strings or defaults load safely.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC37_View_NoRecordAPI",
        "Issue": "29037",
        "Description": "Verify system displays appropriate message when item data API returns no record.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Displays Item Not Found cleanly.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC38_View_ImageLoadFailure",
        "Issue": "29038",
        "Description": "Verify page remains stable when image loading fails due to network issues.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Alt warning tags display without layout breaking.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC39_View_UnauthorizedDirectURL",
        "Issue": "29039",
        "Description": "Verify unauthorized users cannot access the item details page directly via URL.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Redirects back to login or dashboard.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC40_View_APITimeout",
        "Issue": "29040",
        "Description": "Verify system handles API timeout/error while loading item details and shows an appropriate error message.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Toaster details failure alert is displayed.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },

    // ── Edit Item Details Screen: Positive (TC41 to TC45) ──
    {
        "TestID": "TC41_Edit_UpdateSuccess",
        "Issue": "29041",
        "Description": "Verify all item details are updated successfully when valid data is entered and Update Item is clicked.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Updates save successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC42_Edit_AddressFieldsSaved",
        "Issue": "29042",
        "Description": "Verify address fields (Search Address, City, State, Country, Latitude, Longitude) display saved values correctly.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Saved values are visible in form fields.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC43_Edit_MediaImagesDisplayed",
        "Issue": "29043",
        "Description": "Verify uploaded media images (Icon, Thumbnail, Main Photo) are displayed correctly.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Media preview grids display images.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC44_Edit_CancelNoSave",
        "Issue": "29044",
        "Description": "Verify Cancel button navigates back without saving changes.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Redirects back to list without updating values.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC45_Edit_SuccessMessage",
        "Issue": "29045",
        "Description": "Verify success message is displayed after successful item update.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Success toast is displayed.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },

    // ── Edit Item Details Screen: Negative (TC46 to TC50) ──
    {
        "TestID": "TC46_Edit_BlankMandatoryField",
        "Issue": "29046",
        "Description": "Verify validation message appears when a mandatory field is cleared and Update Item is clicked.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Required warning displays; save is blocked.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC47_Edit_InvalidLatLong",
        "Issue": "29047",
        "Description": "Verify invalid latitude or longitude values are rejected during item update.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Validation warns on coordinates format error.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "invalid-lat", "InvalidLongitude": "invalid-long", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC48_Edit_APIFailure",
        "Issue": "29048",
        "Description": "Verify system displays an error message when update API returns failure.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "API update failure toaster shows error.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC49_Edit_BrokenImage",
        "Issue": "29049",
        "Description": "Verify broken or missing image files do not crash the page.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Alternative tags load cleanly; UI remains stable.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC50_Edit_UnauthorizedUpdate",
        "Issue": "29050",
        "Description": "Verify unauthorized users cannot update item details and receive an access denied message.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Save action is blocked; access denied toaster displays.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },

    // ── Item Create Screen: Positive (TC51 to TC60) ──
    {
        "TestID": "TC51_Create_AllMandatoryFields",
        "Issue": "29051",
        "Description": "Verify product is created successfully when all mandatory fields are entered with valid data.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Product creates successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "New Product", "Price": 100, "Quantity": 50, "InventoryType": "In Stock", "StockCount": 10, "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC52_Create_ProductTypeDropdowns",
        "Issue": "29052",
        "Description": "Verify user can select valid Product Type and Type values from dropdowns.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Product dropdown select success.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "Simple", "Type": "Standard", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC53_Create_DealPriceCalculated",
        "Issue": "29053",
        "Description": "Verify Deal Price is calculated/displayed correctly when Price and Discount are entered.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Deal Price auto-calculates.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": 200, "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": 10,
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC54_Create_UploadMediaImages",
        "Issue": "29054",
        "Description": "Verify user can upload valid Icon, Thumbnail, and Main Photo images successfully.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Image files uploaded successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC55_Create_InventoryType",
        "Issue": "29055",
        "Description": "Verify user can select valid Inventory Type and enter Stock Count successfully.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Inventory details populated successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "In Stock", "StockCount": 15, "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC56_Create_TogglesEnabled",
        "Issue": "29056",
        "Description": "Verify user can enable Is Sellable, Available for Quotation, and Price Includes Tax options successfully.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Toggles activate successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC57_Create_BrandAvailability",
        "Issue": "29057",
        "Description": "Verify valid Brand, Availability, Seller Contact, and Freshness Label values are accepted.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Extra attributes saved successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "Brand X", "Availability": "Instock", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC58_Create_AddressDetails",
        "Issue": "29058",
        "Description": "Verify address details (City, State, Country, Latitude, Longitude) are saved correctly with the product.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Coordinates and address match configurations.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "City X", "State": "State X", "Country": "Country X", "Latitude": 40.7128, "Longitude": -74.006,
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC59_Create_MultipleOptionalFields",
        "Issue": "29059",
        "Description": "Verify user can create a product with multiple optional fields populated successfully.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Complex product onboarding finishes successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "Optional Product", "Price": 150, "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "Brand Y", "Availability": "Instock", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC60_Create_SaveSuccess",
        "Issue": "29060",
        "Description": "Verify success message is displayed and product appears in the Item List after clicking Save Item.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Success toast displays; item is active in list grid.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "Save Product", "Price": 120, "Quantity": 30, "InventoryType": "In Stock", "StockCount": 20, "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },

    // ── Item Create Screen: Negative (TC61 to TC70) ──
    {
        "TestID": "TC61_Create_BlankMandatoryFields",
        "Issue": "29061",
        "Description": "Verify validation message appears when mandatory fields are left blank and Save Item is clicked.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Form validation prompts highlight blank required fields.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC62_Create_NonNumericPrice",
        "Issue": "29062",
        "Description": "Verify system rejects non-numeric values entered in Quantity, Price, Discount, Deal Price, or Stock Count fields.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Validation warns on price format error.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "abc", "DuplicateName": ""
    },
    {
        "TestID": "TC63_Create_ZeroPrice",
        "Issue": "29063",
        "Description": "Verify system prevents product creation when Price is less than or equal to zero.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Validation error shows Price must be greater than zero.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": 0, "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC64_Create_InvalidImageFormat",
        "Issue": "29064",
        "Description": "Verify system rejects invalid image formats during Icon, Thumbnail, or Main Photo upload.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Validation blocks invalid image formats.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC65_Create_OversizedImage",
        "Issue": "29065",
        "Description": "Verify system rejects image files exceeding the maximum allowed file size.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Validation blocks file upload.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC66_Create_BlankAvailability",
        "Issue": "29066",
        "Description": "Verify validation message appears when Availability field is left empty.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Validation warns on blank availability.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "Blank Avail", "Price": 50, "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC67_Create_NoInventoryType",
        "Issue": "29067",
        "Description": "Verify system prevents saving when Inventory Type is not selected.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Validation error shows Inventory Type selection is required.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "No Inv", "Price": 40, "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC68_Create_InvalidLatLong",
        "Issue": "29068",
        "Description": "Verify invalid Latitude or Longitude values are not accepted.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Coordinates format validation error triggers.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "invalid", "InvalidLongitude": "invalid", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC69_Create_DuplicateItem",
        "Issue": "29069",
        "Description": "Verify system displays an error message when duplicate product details violate uniqueness rules.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Duplicate item warning toaster displays.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": 10, "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": "Duplicate Item"
    },
    {
        "TestID": "TC70_Create_APIFailure",
        "Issue": "29070",
        "Description": "Verify system handles API/server failure during product creation and displays an appropriate error message.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "API creation failure toaster displays.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },

    // ── Delete Item Popup: Positive (TC71 to TC75) ──
    {
        "TestID": "TC71_Delete_ConfirmDeletes",
        "Issue": "29071",
        "Description": "Verify item is deleted successfully when user clicks \"Yes, delete it\" in the confirmation popup.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Item is removed and list reloads.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC72_Delete_PopupDisplayed",
        "Issue": "29072",
        "Description": "Verify confirmation popup appears with correct warning message when Delete icon is clicked.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Popup warning shows successfully.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC73_Delete_ItemRemovedAfterDelete",
        "Issue": "29073",
        "Description": "Verify item is removed from the item list after successful deletion.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Deleted item is no longer visible.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC74_Delete_CancelKeepsItem",
        "Issue": "29074",
        "Description": "Verify user can close the popup by clicking \"No\" and the item remains unchanged.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Confirmation popup closes; item is retained.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC75_Delete_CancelNoDelete",
        "Issue": "29075",
        "Description": "Verify item is not deleted when user clicks \"No\" in the confirmation popup.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Confirmation popup closes; item is retained in list.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },

    // ── Delete Item Popup: Negative (TC76 to TC78) ──
    {
        "TestID": "TC76_Delete_UnauthorizedUser",
        "Issue": "29076",
        "Description": "Verify unauthorized users cannot delete an item and receive an access denied message.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Action is blocked; access denied toaster displays.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC77_Delete_APIError",
        "Issue": "29077",
        "Description": "Verify system displays an error message when the delete API request fails.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Delete fails showing API error toast.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    },
    {
        "TestID": "TC78_Delete_NetworkFailure",
        "Issue": "29078",
        "Description": "Verify item remains visible in the list if deletion is unsuccessful due to server/network issues.",
        "UserName": "grocery@gmail.com",
        "Password": "Test@123",
        "persona": "seller",
        "ExpectedResult": "Item remains visible in the grid.",
        "Market": "", "Category": "", "ProductCatalog": "", "SearchTerm": "",
        "Name": "", "Price": "", "Quantity": "", "InventoryType": "", "StockCount": "", "ProductType": "", "Type": "", "Discount": "",
        "Brand": "", "Availability": "", "City": "", "State": "", "Country": "", "Latitude": "", "Longitude": "",
        "InvalidLatitude": "", "InvalidLongitude": "", "InvalidPrice": "", "DuplicateName": ""
    }
];

const headers = [
    "TestID",
    "Issue",
    "Description",
    "UserName",
    "Password",
    "persona",
    "ExpectedResult",
    "Market",
    "Category",
    "ProductCatalog",
    "SearchTerm",
    "Name",
    "Price",
    "Quantity",
    "InventoryType",
    "StockCount",
    "ProductType",
    "Type",
    "Discount",
    "Brand",
    "Availability",
    "City",
    "State",
    "Country",
    "Latitude",
    "Longitude",
    "InvalidLatitude",
    "InvalidLongitude",
    "InvalidPrice",
    "DuplicateName"
];

const wsData = [
    headers,
    ...rows.map((r) => headers.map((h) => r[h] || "")),
];

try {
    const wb = XLSX.readFile(FILE);
    const ws = XLSX.utils.aoa_to_sheet(wsData);

    if (wb.SheetNames.includes(SHEET_NAME)) {
        const idx = wb.SheetNames.indexOf(SHEET_NAME);
        wb.SheetNames.splice(idx, 1);
        delete wb.Sheets[SHEET_NAME];
        console.log(`Removed existing sheet: "${SHEET_NAME}"`);
    }

    XLSX.utils.book_append_sheet(wb, ws, SHEET_NAME);
    XLSX.writeFile(wb, FILE);
    console.log(`Successfully updated ${rows.length} rows in '${SHEET_NAME}' sheet in ${FILE}`);
} catch (err) {
    console.error("Failed to update testData.xlsx:", err.message);
    process.exit(1);
}
