/**
 * Creates (or replaces) the "Return Cancellation Regression" sheet in testData.xlsx — 35 test cases.
 * Run once: node scripts/addReturnCancellationPolicySheet.js
 */
const XLSX = require("xlsx");
const path = require("path");

const FILE = path.resolve(__dirname, "../src/resources/data/testData.xlsx");
const SHEET_NAME = "Return Cancellation Regression";

const rows = [
    // ── TC_RCP_001 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_001",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Return & Cancellation Policy page loads via Setup sidebar with all 5 policy tabs visible.",
        "Test Case Type": "Positive",
        "Preconditions": "User is logged in as Tenant admin",
        "Test Steps": "1. From Home page, expand Setup menu in sidebar\n2. Click 'Return & Cancellation'\n3. Verify page heading visible\n4. Verify all 5 tabs (Cancellation, Return, Replacement, Refund, Market Policies) are present",
        "Test Data": "URL: /setup/policy",
        "Expected Result": "Page loads with heading and all 5 tabs visible",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_002 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_002",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify direct URL navigation to /setup/policy loads the Return & Cancellation Policy page.",
        "Test Case Type": "Positive",
        "Preconditions": "User is logged in as Tenant admin",
        "Test Steps": "1. Navigate directly to /setup/policy\n2. Verify page heading is visible\n3. Verify URL contains 'setup/policy'",
        "Test Data": "URL: /setup/policy",
        "Expected Result": "Page loads correctly with heading visible on direct navigation",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_003 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_003",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Cancellation tab is active and displays all required fields.",
        "Test Case Type": "Positive",
        "Preconditions": "User is on Return & Cancellation Policy page",
        "Test Steps": "1. Navigate to /setup/policy\n2. Click Cancellation tab\n3. Verify Window Minutes, Allowed Before Statuses, Free Cancellation Before Status, Fee Type, Cancellation Fee, Reasons fields are visible",
        "Test Data": "Tab: Cancellation",
        "Expected Result": "All Cancellation tab fields (Window Minutes, statuses, fee type, reasons) are visible",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_004 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_004",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify enabling Cancellation policy toggle and saving persists the enabled state.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Enable the Enabled toggle\n3. Click Save\n4. Re-navigate to page\n5. Verify toggle is still enabled",
        "Test Data": "Enabled: true",
        "Expected Result": "Cancellation policy is enabled and persists after page reload",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_005 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_005",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify disabling Cancellation policy collapses conditional fields and saves.",
        "Test Case Type": "Negative",
        "Preconditions": "Cancellation policy is currently enabled",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Disable the Enabled toggle\n3. Click Save\n4. Verify save succeeds\n5. Re-enable for clean state",
        "Test Data": "Enabled: false",
        "Expected Result": "Cancellation policy disabled state saves successfully; conditional fields hidden",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_006 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_006",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Window Minutes accepts 0 (no time limit) and shows hint text.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active and Enabled toggle is ON",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Set Window Minutes to 0\n3. Verify '0 = no time limit' hint appears\n4. Click Save and verify success",
        "Test Data": "Window Minutes: 0",
        "Expected Result": "Window Minutes 0 accepted, hint shown, save succeeds",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_007 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_007",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Window Minutes accepts a valid positive value (60) and saves correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active and Enabled toggle is ON",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Set Window Minutes to 60\n3. Click Save\n4. Verify success toast",
        "Test Data": "Window Minutes: 60",
        "Expected Result": "Window Minutes 60 saved; success feedback displayed",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_008 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_008",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Allowed Before Statuses multi-select adds PAYMENT_CONFIRMED and saves.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active and Enabled toggle is ON",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Open Allowed Before Statuses dropdown\n3. Select PAYMENT_CONFIRMED\n4. Click Save\n5. Verify success",
        "Test Data": "Status: PAYMENT_CONFIRMED",
        "Expected Result": "PAYMENT_CONFIRMED added to Allowed Before Statuses; saved successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_009 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_009",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Free Cancellation Before Status single-select selects INVENTORY_CONFIRMED and saves.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active and Enabled toggle is ON",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Open Free Cancellation Before Status dropdown\n3. Select INVENTORY_CONFIRMED\n4. Click Save\n5. Verify success",
        "Test Data": "Status: INVENTORY_CONFIRMED",
        "Expected Result": "INVENTORY_CONFIRMED selected and saved successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_010 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_010",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Fee Type FLAT with Cancellation Fee 50 saves correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active and Enabled toggle is ON",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Select FLAT fee type\n3. Enter Cancellation Fee as 50\n4. Click Save\n5. Verify success",
        "Test Data": "Fee Type: FLAT, Fee: 50",
        "Expected Result": "FLAT fee type with 50 cancellation fee saved successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_011 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_011",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Fee Type PERCENTAGE with 10% saves correctly and resets to FLAT/0 afterwards.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active and Enabled toggle is ON",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Select PERCENTAGE fee type\n3. Enter 10 as fee\n4. Click Save\n5. Verify success\n6. Reset to FLAT/0",
        "Test Data": "Fee Type: PERCENTAGE, Fee: 10",
        "Expected Result": "PERCENTAGE fee type with 10% saved successfully; can be reset to FLAT/0",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_012 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_012",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Auto Refund On Approval toggle saves and persists after reload.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active and Enabled toggle is ON",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Enable Auto Refund On Approval toggle\n3. Click Save\n4. Re-navigate to page\n5. Verify toggle is still enabled",
        "Test Data": "Auto Refund On Approval: true",
        "Expected Result": "Auto Refund On Approval toggle state persists after save and reload",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_013 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_013",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify COD Allowed toggle can be disabled and settings persist after save.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active and Enabled toggle is ON",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Disable COD Allowed toggle\n3. Click Save\n4. Verify success\n5. Re-enable for clean state",
        "Test Data": "COD Allowed: false",
        "Expected Result": "COD Allowed disabled state saves; re-enable restores default",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_014 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_014",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify adding a custom cancellation reason tag persists after save.",
        "Test Case Type": "Positive",
        "Preconditions": "Cancellation tab is active and Enabled toggle is ON",
        "Test Steps": "1. Navigate to Cancellation tab\n2. Type 'DAMAGED_PACKAGING' in Reasons input\n3. Press Enter to create tag\n4. Click Save\n5. Verify save succeeds",
        "Test Data": "Custom Reason: DAMAGED_PACKAGING",
        "Expected Result": "Custom reason tag added and saved successfully",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_015 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_015",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Return tab displays all required fields: Window Days, Item Types, Shipping Paid By, Restocking Fee.",
        "Test Case Type": "Positive",
        "Preconditions": "User is on Return & Cancellation Policy page",
        "Test Steps": "1. Navigate to Return & Cancellation Policy\n2. Click Return tab\n3. Verify Window Days, Returnable Item Types, Non Returnable Item Types, Shipping Paid By, Restocking Fee fields are visible",
        "Test Data": "Tab: Return",
        "Expected Result": "Return tab shows Window Days, item type fields, Shipping Paid By, Restocking Fee",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_016 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_016",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify enabling Return policy with Window Days 7 saves successfully.",
        "Test Case Type": "Positive",
        "Preconditions": "Return tab is active",
        "Test Steps": "1. Click Return tab\n2. Enable the Enabled toggle\n3. Set Window Days to 7\n4. Click Save\n5. Verify success",
        "Test Data": "Window Days: 7, Enabled: true",
        "Expected Result": "Return policy enabled with 7-day window saves successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_017 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_017",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify disabling Return policy toggle and saving succeeds.",
        "Test Case Type": "Negative",
        "Preconditions": "Return policy is currently enabled",
        "Test Steps": "1. Click Return tab\n2. Disable the Enabled toggle\n3. Click Save\n4. Verify save succeeds\n5. Re-enable for clean state",
        "Test Data": "Enabled: false",
        "Expected Result": "Return policy disabled state saves; restore to enabled for clean state",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_018 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_018",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify adding returnable item type 'ELECTRONICS' as a tag and saving.",
        "Test Case Type": "Positive",
        "Preconditions": "Return tab is active and Enabled toggle is ON",
        "Test Steps": "1. Click Return tab\n2. Type 'ELECTRONICS' in Returnable Item Types input\n3. Press Enter\n4. Click Save\n5. Verify success",
        "Test Data": "Item Type: ELECTRONICS",
        "Expected Result": "ELECTRONICS tag added to Returnable Item Types and saved",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_019 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_019",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify enabling Require Images and setting Min Images to 2 saves correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Return tab is active and Enabled toggle is ON",
        "Test Steps": "1. Click Return tab\n2. Enable Require Images toggle\n3. Set Min Images to 2\n4. Click Save\n5. Verify success",
        "Test Data": "Require Images: true, Min Images: 2",
        "Expected Result": "Require Images enabled with Min Images 2 saved successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_020 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_020",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Restocking Fee (FLAT) set to 25 is saved correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Return tab is active and Enabled toggle is ON",
        "Test Steps": "1. Click Return tab\n2. Enter 25 in Restocking Fee field\n3. Click Save\n4. Verify success",
        "Test Data": "Restocking Fee: 25 (FLAT)",
        "Expected Result": "Restocking Fee 25 saved; applied during return approval",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_021 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_021",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Replacement tab displays Window Days, Shipping Paid By, Max Per Order, Require Original Return, Require Images fields.",
        "Test Case Type": "Positive",
        "Preconditions": "User is on Return & Cancellation Policy page",
        "Test Steps": "1. Click Replacement tab\n2. Verify Window Days, Shipping Paid By, Max Per Order, Require Original Return, Require Images fields visible",
        "Test Data": "Tab: Replacement",
        "Expected Result": "Replacement tab shows all expected fields",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_022 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_022",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify enabling Replacement with Window Days 14 and Max Per Order 2 saves correctly.",
        "Test Case Type": "Positive",
        "Preconditions": "Replacement tab is active",
        "Test Steps": "1. Click Replacement tab\n2. Enable Enabled toggle\n3. Set Window Days to 14\n4. Set Max Per Order to 2\n5. Click Save\n6. Verify success",
        "Test Data": "Enabled: true, Window Days: 14, Max Per Order: 2",
        "Expected Result": "Replacement configured with 14-day window and max 2 per order saves successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_023 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_023",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Require Original Return toggle saves and persists after reload.",
        "Test Case Type": "Positive",
        "Preconditions": "Replacement tab is active and Enabled toggle is ON",
        "Test Steps": "1. Click Replacement tab\n2. Enable Require Original Return toggle\n3. Click Save\n4. Re-navigate to page\n5. Verify Require Original Return is still enabled",
        "Test Data": "Require Original Return: true",
        "Expected Result": "Require Original Return toggle persists after save and page reload",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_024 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_024",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Require Images toggle on Replacement tab can be enabled and saved.",
        "Test Case Type": "Positive",
        "Preconditions": "Replacement tab is active and Enabled toggle is ON",
        "Test Steps": "1. Click Replacement tab\n2. Enable Require Images toggle\n3. Click Save\n4. Verify success",
        "Test Data": "Require Images: true (Replacement)",
        "Expected Result": "Require Images toggle enabled and saved on Replacement tab",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_025 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_025",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify disabling Replacement policy saves and can be re-enabled for clean state.",
        "Test Case Type": "Negative",
        "Preconditions": "Replacement policy is currently enabled",
        "Test Steps": "1. Click Replacement tab\n2. Disable Enabled toggle\n3. Click Save\n4. Verify success\n5. Re-enable for clean state",
        "Test Data": "Enabled: false (Replacement)",
        "Expected Result": "Replacement disabled state saves; restore to enabled",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_026 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_026",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Refund tab displays Refund Method, COD Refund Method, Processing Days, and refund toggle fields.",
        "Test Case Type": "Positive",
        "Preconditions": "User is on Return & Cancellation Policy page",
        "Test Steps": "1. Click Refund tab\n2. Verify Refund Method, COD Refund Method, Processing Days, Partial Refund Allowed, Shipping Refundable, Deduct Cancellation Fee, Deduct Restocking Fee fields are visible",
        "Test Data": "Tab: Refund",
        "Expected Result": "All Refund tab fields are visible",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_027 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_027",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Refund Method (ORIGINAL_PAYMENT), COD Refund Method (WALLET), Processing Days 7 saves.",
        "Test Case Type": "Positive",
        "Preconditions": "Refund tab is active",
        "Test Steps": "1. Click Refund tab\n2. Set Refund Method to ORIGINAL_PAYMENT\n3. Set COD Refund Method to WALLET\n4. Set Processing Days to 7\n5. Click Save\n6. Verify success",
        "Test Data": "Refund: ORIGINAL_PAYMENT, COD: WALLET, Days: 7",
        "Expected Result": "Refund configuration saves successfully",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_028 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_028",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Partial Refund Allowed and Shipping Refundable toggles save and Partial Refund Allowed persists.",
        "Test Case Type": "Positive",
        "Preconditions": "Refund tab is active",
        "Test Steps": "1. Click Refund tab\n2. Enable Partial Refund Allowed toggle\n3. Enable Shipping Refundable toggle\n4. Click Save\n5. Re-navigate and verify Partial Refund Allowed is ON",
        "Test Data": "Partial Refund: true, Shipping Refundable: true",
        "Expected Result": "Both toggles enabled and Partial Refund Allowed persists after reload",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_029 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_029",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Deduct Cancellation Fee and Deduct Restocking Fee toggles save and Deduct Cancellation Fee persists.",
        "Test Case Type": "Positive",
        "Preconditions": "Refund tab is active",
        "Test Steps": "1. Click Refund tab\n2. Enable Deduct Cancellation Fee\n3. Enable Deduct Restocking Fee\n4. Click Save\n5. Re-navigate and verify Deduct Cancellation Fee is ON",
        "Test Data": "Deduct Cancel Fee: true, Deduct Restocking Fee: true",
        "Expected Result": "Both deduct toggles saved; Deduct Cancellation Fee persists after reload",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_030 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_030",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify Market Policies tab loads with Add Market button and empty-state or existing market list.",
        "Test Case Type": "Positive",
        "Preconditions": "User is on Return & Cancellation Policy page",
        "Test Steps": "1. Click Market Policies tab\n2. Verify '+ Add Market' button is visible\n3. Verify empty state 'No market overrides configured' OR existing market rows are shown",
        "Test Data": "Tab: Market Policies",
        "Expected Result": "Market Policies tab loads with Add Market button and empty state or market entries",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_031 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_031",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify clicking Add Market button opens Market Policy Override modal with all required fields.",
        "Test Case Type": "Positive",
        "Preconditions": "Market Policies tab is active",
        "Test Steps": "1. Click Market Policies tab\n2. Click '+ Add Market'\n3. Verify modal opens with Market Name, Conditions fields\n4. Verify Override Cancellation/Return/Replacement/Refund toggles visible\n5. Click Cancel",
        "Test Data": "Modal: Market Policy Override",
        "Expected Result": "Modal opens with all override fields; Cancel closes it without saving",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_032 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_032",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify cancelling Market Policy modal discards changes without creating a new market override.",
        "Test Case Type": "Negative",
        "Preconditions": "Market Policies tab is active",
        "Test Steps": "1. Click Market Policies tab\n2. Note current market count\n3. Click '+ Add Market'\n4. Click Cancel without filling any fields\n5. Verify modal is closed and no new market entry appeared",
        "Test Data": "Cancel without save",
        "Expected Result": "Market modal closed; no new market override added on cancel",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_033 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_033",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify unauthenticated user cannot access Return & Cancellation Policy page directly.",
        "Test Case Type": "Negative",
        "Preconditions": "User is NOT logged in",
        "Test Steps": "1. Open browser without authenticated session\n2. Navigate directly to /setup/policy\n3. Verify user is redirected to login page or access denied",
        "Test Data": "URL: /setup/policy, No auth",
        "Expected Result": "Unauthenticated access redirected to login page or access denied shown",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_034 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_034",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify API failure on Policy page load is handled gracefully without a JavaScript crash.",
        "Test Case Type": "Negative",
        "Preconditions": "User is logged in as Tenant admin",
        "Test Steps": "1. Navigate to /setup/policy\n2. Intercept and abort the policy API call\n3. Reload the page\n4. Verify app does not show uncaught JavaScript error",
        "Test Data": "Simulated API failure",
        "Expected Result": "App handles API failure gracefully — no uncaught JavaScript errors in page body",
        "Priority": "Medium",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
    // ── TC_RCP_035 ────────────────────────────────────────────────────────────
    {
        "Test Case ID": "TC_RCP_035",
        "Module": "Setup",
        "Screen Name": "Return & Cancellation Policy",
        "Test Scenario": "Verify full cross-tab regression: configure and save Cancellation, Return, Replacement, and Refund tabs in sequence.",
        "Test Case Type": "Positive",
        "Preconditions": "User is logged in as Tenant admin",
        "Test Steps": "1. Configure Cancellation tab (Enabled, Window 0, FLAT 0) and Save\n2. Configure Return tab (Enabled, Window 7) and Save\n3. Configure Replacement tab (Enabled, Window 7, Max 1) and Save\n4. Configure Refund tab (ORIGINAL_PAYMENT, Days 7) and Save\n5. Verify each save succeeds",
        "Test Data": "All tabs default/baseline values",
        "Expected Result": "All 4 policy tabs configured and saved in sequence without errors",
        "Priority": "High",
        "Status": "Not Executed",
        "Actual Result": "",
        "Screenshot Path": "",
        "Execution Time": "",
    },
];

const headers = [
    "Test Case ID",
    "Module",
    "Screen Name",
    "Test Scenario",
    "Test Case Type",
    "Preconditions",
    "Test Steps",
    "Test Data",
    "Expected Result",
    "Priority",
    "Status",
    "Actual Result",
    "Screenshot Path",
    "Execution Time",
];

const wsData = [
    headers,
    ...rows.map((r) => headers.map((h) => r[h] || "")),
];

const wb = XLSX.readFile(FILE);
const ws = XLSX.utils.aoa_to_sheet(wsData);

if (wb.SheetNames.includes(SHEET_NAME)) {
    const idx = wb.SheetNames.indexOf(SHEET_NAME);
    wb.SheetNames.splice(idx, 1);
    delete wb.Sheets[SHEET_NAME];
}
XLSX.utils.book_append_sheet(wb, ws, SHEET_NAME);
XLSX.writeFile(wb, FILE);
console.log(`Written ${rows.length} rows to '${SHEET_NAME}' sheet in ${FILE}`);
