/**
 * Updates (or replaces) the "ServiceTicketTest" sheet in testData.xlsx — 42 test cases.
 * Run once: node scripts/addServiceTicketTestSheet.js
 */
const XLSX = require("xlsx");
const path = require("path");

const FILE = path.resolve(__dirname, "../src/resources/data/testData.xlsx");
const SHEET_NAME = "ServiceTicketTest";

const rows = [
    // ── Preserved Spec-Required Test Cases ──
    {
        "TestID": "TC01_ViewAndCloseServiceTicket",
        "Issue": "5001",
        "Description": "Verify user can successfully update the service ticket by modifying status and notes.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "Biswarup Roy",
        "Subject": "Test",
        "Status": "OPEN",
        "NewStatus": "CLOSED",
        "NoteToCustomer": "Ticket closed successfully",
        "InternalNote": "Closed by automation test",
        "ExpectedResult": "Ticket status is updated and saved successfully."
    },
    {
        "TestID": "TC02_InvalidTicketID",
        "Issue": "5002",
        "Description": "Verify searching with an invalid Ticket ID returns no results.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR9999999999",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "No data available message is displayed correctly."
    },

    // ── Service Tickets Screen: Positives ──
    {
        "TestID": "TC_ST_POS_01",
        "Issue": "51001",
        "Description": "Verify Service Tickets page loads successfully with all widgets and ticket data.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Service Tickets dashboard page loads with search input, filters, tabs, and tickets list visible."
    },
    {
        "TestID": "TC_ST_POS_02",
        "Issue": "51002",
        "Description": "Verify user can search tickets using a valid Ticket ID.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "The exact ticket matching the searched ID is returned and shown in the grid."
    },
    {
        "TestID": "TC_ST_POS_03",
        "Issue": "51003",
        "Description": "Verify user can filter tickets by Status and view matching results.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "OPEN",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Only tickets with the selected status (e.g. OPEN) are displayed."
    },
    {
        "TestID": "TC_ST_POS_04",
        "Issue": "51004",
        "Description": "Verify user can filter tickets by Category and view matching records.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Tickets are filtered successfully and display only records matching the category."
    },
    {
        "TestID": "TC_ST_POS_05",
        "Issue": "51005",
        "Description": "Verify clicking the View icon opens the correct ticket details.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Redirects to View Details page displaying matching ticket information."
    },
    {
        "TestID": "TC_ST_POS_06",
        "Issue": "51006",
        "Description": "Verify clicking the Edit icon opens the selected ticket for modification.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Update Service Ticket screen opens with pre-populated field values."
    },
    {
        "TestID": "TC_ST_POS_07",
        "Issue": "51007",
        "Description": "Verify Export button downloads the ticket data successfully.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "CSV file of ticket records is downloaded successfully."
    },
    {
        "TestID": "TC_ST_POS_08",
        "Issue": "51008",
        "Description": "Verify Refresh button reloads the latest ticket information.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "The latest service ticket records are fetched and reloaded."
    },
    {
        "TestID": "TC_ST_POS_09",
        "Issue": "51009",
        "Description": "Verify pagination navigates correctly between pages.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Next and previous page buttons successfully page through lists."
    },
    {
        "TestID": "TC_ST_POS_10",
        "Issue": "51010",
        "Description": "Verify ticket counts displayed in tabs match the corresponding records.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Count badges on tabs accurately show current ticket volume matching actual list items."
    },

    // ── Service Tickets Screen: Negatives ──
    {
        "TestID": "TC_ST_NEG_02",
        "Issue": "51012",
        "Description": "Verify searching with special characters does not break the application.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR#@!$%^",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Application handles inputs safely without error and displays no records found."
    },
    {
        "TestID": "TC_ST_NEG_03",
        "Issue": "51013",
        "Description": "Verify applying filters with no matching data displays an appropriate message.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Displays 'No service tickets matched' or empty status message cleanly."
    },
    {
        "TestID": "TC_ST_NEG_04",
        "Issue": "51014",
        "Description": "Verify user cannot access details of a non-existent ticket.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR0000000000",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "System blocks navigation or alerts that ticket cannot be found."
    },
    {
        "TestID": "TC_ST_NEG_05",
        "Issue": "51015",
        "Description": "Verify Export functionality handles zero records gracefully.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Export displays error toast or downloads empty structure safely."
    },
    {
        "TestID": "TC_ST_NEG_06",
        "Issue": "51016",
        "Description": "Verify pagination does not navigate beyond available pages.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Pagination navigation controls are disabled on first and last pages."
    },
    {
        "TestID": "TC_ST_NEG_07",
        "Issue": "51017",
        "Description": "Verify application handles rapid multiple filter selections without errors.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "System debounces filter clicks and serves the latest selection."
    },
    {
        "TestID": "TC_ST_NEG_08",
        "Issue": "51018",
        "Description": "Verify search field handles excessively long input values correctly.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR" + "9".repeat(100),
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Input limits characters or reports search values not found safely."
    },
    {
        "TestID": "TC_ST_NEG_09",
        "Issue": "51019",
        "Description": "Verify ticket list displays an error message when API response fails.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "System triggers API error alert and displays empty layout gracefully."
    },
    {
        "TestID": "TC_ST_NEG_10",
        "Issue": "51020",
        "Description": "Verify Refresh button handles network interruption gracefully.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Refreshing stops and showing offline warning toaster."
    },

    // ── Service Tickets View Details Screen: Positives ──
    {
        "TestID": "TC_ST_VIEW_POS_01",
        "Issue": "52001",
        "Description": "Verify ticket details page loads successfully with correct ticket information.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Ticket Details panel elements render properly with correct ID, subject, and customer profile."
    },
    {
        "TestID": "TC_ST_VIEW_POS_02",
        "Issue": "52002",
        "Description": "Verify user can navigate back to the Service Ticket list by clicking the Back button.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Clicking Back redirects user to the main tickets list."
    },
    {
        "TestID": "TC_ST_VIEW_POS_03",
        "Issue": "52003",
        "Description": "Verify clicking the Edit button opens the ticket edit screen with pre-populated data.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Update Service Ticket screen is loaded with correct data inputs filled in."
    },
    {
        "TestID": "TC_ST_VIEW_POS_04",
        "Issue": "52004",
        "Description": "Verify clicking the Reopen button successfully changes the ticket status from Closed/Open to Reopened.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Status is updated to REOPENED and success message appears."
    },
    {
        "TestID": "TC_ST_VIEW_POS_05",
        "Issue": "52005",
        "Description": "Verify customer information (Name, Phone, Email, Prior Tickets) is displayed correctly.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Customer panel values match selected ticket customer information."
    },
    {
        "TestID": "TC_ST_VIEW_POS_06",
        "Issue": "52006",
        "Description": "Verify Conversation & Work Notes section displays all ticket communication history accurately.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "All communication items and timeline events list accurately."
    },

    // ── Service Tickets View Details Screen: Negatives ──
    {
        "TestID": "TC_ST_VIEW_NEG_01",
        "Issue": "52007",
        "Description": "Verify system displays an appropriate message when ticket details fail to load due to API failure.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Fail status handles safely, alert shows info error."
    },
    {
        "TestID": "TC_ST_VIEW_NEG_02",
        "Issue": "52008",
        "Description": "Verify clicking Edit without sufficient permissions displays an authorization error.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Access is blocked, displaying Permission Denied error."
    },
    {
        "TestID": "TC_ST_VIEW_NEG_03",
        "Issue": "52009",
        "Description": "Verify user cannot reopen a ticket if reopen action is restricted by business rules.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Reopen triggers business rule restriction toast."
    },
    {
        "TestID": "TC_ST_VIEW_NEG_04",
        "Issue": "52010",
        "Description": "Verify customer section handles missing customer data without UI breakage.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Handles empty strings cleanly displaying placeholders."
    },
    {
        "TestID": "TC_ST_VIEW_NEG_05",
        "Issue": "52011",
        "Description": "Verify Conversation & Work Notes section displays an empty-state message when no notes exist.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Displays 'No conversation history' empty view."
    },
    {
        "TestID": "TC_ST_VIEW_NEG_06",
        "Issue": "52012",
        "Description": "Verify SLA section handles missing or invalid SLA data without displaying incorrect metrics.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "SLA countdown shows empty/dash status safely."
    },

    // ── Update Service Ticket Screen: Positives ──
    {
        "TestID": "TC_ST_UPDATE_POS_02",
        "Issue": "53002",
        "Description": "Verify user can change the ticket status and save the updated status successfully.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "OPEN",
        "NewStatus": "CLOSED",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Ticket status changes successfully and updates are saved."
    },
    {
        "TestID": "TC_ST_UPDATE_POS_03",
        "Issue": "53003",
        "Description": "Verify user can add a valid Note to Customer and the note is saved in the customer history section.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "Your issue is resolved.",
        "InternalNote": "",
        "ExpectedResult": "Customer note is recorded and displays in communications timeline."
    },
    {
        "TestID": "TC_ST_UPDATE_POS_04",
        "Issue": "53004",
        "Description": "Verify user can add an Internal Note and it is saved successfully without being visible to the customer.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "Internal update note.",
        "ExpectedResult": "Internal Note is added to backend logs but remains hidden on client portal."
    },
    {
        "TestID": "TC_ST_UPDATE_POS_05",
        "Issue": "53005",
        "Description": "Verify user can reassign the ticket by updating the Assign To field and saving the changes.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Ticket is assigned to a different operator successfully."
    },

    // ── Update Service Ticket Screen: Negatives ──
    {
        "TestID": "TC_ST_UPDATE_NEG_01",
        "Issue": "53006",
        "Description": "Verify system displays a validation error when mandatory fields are left blank and Update is clicked.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Validation error highlights blank inputs and prevents save."
    },
    {
        "TestID": "TC_ST_UPDATE_NEG_02",
        "Issue": "53007",
        "Description": "Verify user cannot enter more than the allowed character limit in the Note to Customer field.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "A".repeat(5001),
        "InternalNote": "",
        "ExpectedResult": "Text entry is cut off or reports character limit warning."
    },
    {
        "TestID": "TC_ST_UPDATE_NEG_03",
        "Issue": "53008",
        "Description": "Verify system prevents saving an invalid or unsupported ticket status.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "INVALID_STATUS",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Dropdown validator blocks entry or API rejects update."
    },
    {
        "TestID": "TC_ST_UPDATE_NEG_04",
        "Issue": "53009",
        "Description": "Verify application handles invalid customer email format without saving the ticket.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Email input highlights error and update is blocked."
    },
    {
        "TestID": "TC_ST_UPDATE_NEG_05",
        "Issue": "53010",
        "Description": "Verify clicking Update during an API/network failure displays an appropriate error message and does not save changes.",
        "UserName": "freshcart@gmail.com",
        "Password": "Welcome@123",
        "persona": "tenant",
        "TicketID": "SR6351088432",
        "CustomerName": "",
        "Subject": "",
        "Status": "",
        "NewStatus": "",
        "NoteToCustomer": "",
        "InternalNote": "",
        "ExpectedResult": "Error toaster triggers, system retries or cancels safely without changing local data."
    }
];

const headers = [
    "TestID",
    "Issue",
    "Description",
    "UserName",
    "Password",
    "persona",
    "TicketID",
    "CustomerName",
    "Subject",
    "Status",
    "NewStatus",
    "NoteToCustomer",
    "InternalNote",
    "ExpectedResult"
];

const wsData = [
    headers,
    ...rows.map((r) => headers.map((h) => r[h] || "")),
];

try {
    const wb = XLSX.readFile(FILE);
    const ws = XLSX.utils.aoa_to_sheet(wsData);

    if (wb.SheetNames.includes(SHEET_NAME)) {
        const idx = wb.SheetNames.indexOf(SHEET_NAME);
        wb.SheetNames.splice(idx, 1);
        delete wb.Sheets[SHEET_NAME];
        console.log(`Removed existing sheet: "${SHEET_NAME}"`);
    }

    XLSX.utils.book_append_sheet(wb, ws, SHEET_NAME);
    XLSX.writeFile(wb, FILE);
    console.log(`Successfully updated ${rows.length} rows in '${SHEET_NAME}' sheet in ${FILE}`);
} catch (err) {
    console.error("Failed to update testData.xlsx:", err.message);
    process.exit(1);
}
