/**
 * Updates (or replaces) the "Subscription Plan( Tenant)" sheet in testData.xlsx — 30 test cases.
 * Run once: node scripts/addSubscriptionPlanTenantSheet.js
 */
const XLSX = require("xlsx");
const path = require("path");

const FILE = path.resolve(__dirname, "../src/resources/data/testData.xlsx");
const SHEET_NAME = "Subscription Plan( Tenant)";

const rows = [
    // ── Positive Test Cases (TC_SP_01 to TC_SP_15) ──
    {
        "TC_ID": "TC_SP_01",
        "Type": "Positive",
        "Expected_Result": "Verify user can successfully create a subscription plan with all mandatory valid inputs.",
        "Description": "Verify user can successfully create a subscription plan with all mandatory valid inputs.",
        "Plan_Name": "BasicPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_02",
        "Type": "Positive",
        "Expected_Result": "Verify user can select Scope, Org Access Level, Payment Type, and Cadence Type from dropdowns successfully.",
        "Description": "Verify user can select Scope, Org Access Level, Payment Type, and Cadence Type from dropdowns successfully.",
        "Plan_Name": "PlanTwo",
        "Scope": "PARTNER",
        "Org_Access": "SPECIFIC",
        "Payment_Type": "PRE-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "29.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "WEEKLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "7",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_03",
        "Type": "Positive",
        "Expected_Result": "Verify Price field accepts valid numeric and decimal values correctly.",
        "Description": "Verify Price field accepts valid numeric and decimal values correctly.",
        "Plan_Name": "PlanThree",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "49.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_04",
        "Type": "Positive",
        "Expected_Result": "Verify Auto Renewal toggle can be enabled successfully during plan creation.",
        "Description": "Verify Auto Renewal toggle can be enabled successfully during plan creation.",
        "Plan_Name": "PlanFour",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "9.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_05",
        "Type": "Positive",
        "Expected_Result": "Verify user can add single and multiple Features successfully.",
        "Description": "Verify user can add single and multiple Features successfully.",
        "Plan_Name": "PlanFive",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "15.00",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "Feature B"
    },
    {
        "TC_ID": "TC_SP_06",
        "Type": "Positive",
        "Expected_Result": "Verify Plan Preview section updates dynamically when form values are changed.",
        "Description": "Verify Plan Preview section updates dynamically when form values are changed.",
        "Plan_Name": "PreviewPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "100.00",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "YEARLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "365",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_07",
        "Type": "Positive",
        "Expected_Result": "Verify Create Plan button successfully creates a new subscription plan and redirects to listing page.",
        "Description": "Verify Create Plan button successfully creates a new subscription plan and redirects to listing page.",
        "Plan_Name": "CreatePlanPos",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "99.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_08",
        "Type": "Positive",
        "Expected_Result": "Verify newly created subscription plan appears correctly in Subscription Plans table.",
        "Description": "Verify newly created subscription plan appears correctly in Subscription Plans table.",
        "Plan_Name": "VerifyInTable",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "5.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_09",
        "Type": "Positive",
        "Expected_Result": "Verify Search functionality returns correct results based on Plan Name.",
        "Description": "Verify Search functionality returns correct results based on Plan Name.",
        "Plan_Name": "SearchPlanPos",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_10",
        "Type": "Positive",
        "Expected_Result": "Verify Scope filter displays only matching subscription plans.",
        "Description": "Verify Scope filter displays only matching subscription plans.",
        "Plan_Name": "ScopeFilterPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_11",
        "Type": "Positive",
        "Expected_Result": "Verify user can open Subscription Plan details page using View icon.",
        "Description": "Verify user can open Subscription Plan details page using View icon.",
        "Plan_Name": "ViewIconPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "15.00",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_12",
        "Type": "Positive",
        "Expected_Result": "Verify Edit Subscription Plan page loads existing data correctly.",
        "Description": "Verify Edit Subscription Plan page loads existing data correctly.",
        "Plan_Name": "EditLoadPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_13",
        "Type": "Positive",
        "Expected_Result": "Verify user can successfully update Plan Name, Price, and Features from Edit page.",
        "Description": "Verify user can successfully update Plan Name, Price, and Features from Edit page.",
        "Plan_Name": "EditUpdatePlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "25.00",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_14",
        "Type": "Positive",
        "Expected_Result": "Verify updated subscription plan details are reflected correctly in listing and details page.",
        "Description": "Verify updated subscription plan details are reflected correctly in listing and details page.",
        "Plan_Name": "ReflectUpdatePlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "20.00",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_15",
        "Type": "Positive",
        "Expected_Result": "Verify pagination works correctly when navigating between multiple subscription plan pages.",
        "Description": "Verify pagination works correctly when navigating between multiple subscription plan pages.",
        "Plan_Name": "PaginationPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },

    // ── Negative Test Cases (TC_SP_NEG_01 to TC_SP_NEG_15) ──
    {
        "TC_ID": "TC_SP_NEG_01",
        "Type": "Negative",
        "Expected_Result": "Verify error message is displayed when Plan Name field is left blank during plan creation.",
        "Description": "Verify error message is displayed when Plan Name field is left blank during plan creation.",
        "Plan_Name": "",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "10.00",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_02",
        "Type": "Negative",
        "Expected_Result": "Verify system prevents creation when mandatory fields are empty.",
        "Description": "Verify system prevents creation when mandatory fields are empty.",
        "Plan_Name": "EmptyMandatory",
        "Scope": "",
        "Org_Access": "",
        "Payment_Type": "",
        "Tax_Code": "",
        "Charge_Code": "",
        "Currency": "",
        "Price": "",
        "UOM": "",
        "Base_Qty": "",
        "Cadence": "",
        "Auto_Renewal": "",
        "Plan_Type": "",
        "Validity_Days": "",
        "Feature1": "",
        "Feature2": ""
    },
    {
        "TC_ID": "TC_SP_NEG_03",
        "Type": "Negative",
        "Expected_Result": "Verify Price field does not accept alphabets or special characters.",
        "Description": "Verify Price field does not accept alphabets or special characters.",
        "Plan_Name": "InvalidPrice",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "invalid-price-abc",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_04",
        "Type": "Negative",
        "Expected_Result": "Verify Base Quantity field rejects negative and zero values.",
        "Description": "Verify Base Quantity field rejects negative and zero values.",
        "Plan_Name": "InvalidQty",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "-5",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_05",
        "Type": "Negative",
        "Expected_Result": "Verify Validity Days field does not accept non-numeric input.",
        "Description": "Verify Validity Days field does not accept non-numeric input.",
        "Plan_Name": "InvalidValidity",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "abc",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_06",
        "Type": "Negative",
        "Expected_Result": "Verify duplicate Plan Name cannot be created successfully.",
        "Description": "Verify duplicate Plan Name cannot be created successfully.",
        "Plan_Name": "DupPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_07",
        "Type": "Negative",
        "Expected_Result": "Verify Description field validation appears when character limit is exceeded.",
        "Description": "Verify Description field validation appears when character limit is exceeded.",
        "Plan_Name": "LongDescPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_08",
        "Type": "Negative",
        "Expected_Result": "Verify system prevents saving when invalid Tax Code is entered.",
        "Description": "Verify system prevents saving when invalid Tax Code is entered.",
        "Plan_Name": "InvalidTaxPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "INVALID_TAX",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_09",
        "Type": "Negative",
        "Expected_Result": "Verify user cannot create plan without selecting Scope dropdown value.",
        "Description": "Verify user cannot create plan without selecting Scope dropdown value.",
        "Plan_Name": "NoScopePlan",
        "Scope": "",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_10",
        "Type": "Negative",
        "Expected_Result": "Verify blank Feature field cannot be added successfully.",
        "Description": "Verify blank Feature field cannot be added successfully.",
        "Plan_Name": "BlankFeaturePlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "",
        "Feature2": ""
    },
    {
        "TC_ID": "TC_SP_NEG_11",
        "Type": "Negative",
        "Expected_Result": "Verify system shows validation when Currency field is not selected.",
        "Description": "Verify system shows validation when Currency field is not selected.",
        "Plan_Name": "NoCurrencyPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_12",
        "Type": "Negative",
        "Expected_Result": "Verify invalid Cadence Type selection is not accepted by the system.",
        "Description": "Verify invalid Cadence Type selection is not accepted by the system.",
        "Plan_Name": "InvalidCadencePlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "INVALID_CADENCE",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_13",
        "Type": "Negative",
        "Expected_Result": "Verify Create Plan button does not work when internet/API failure occurs.",
        "Description": "Verify Create Plan button does not work when internet/API failure occurs.",
        "Plan_Name": "APIFailPlan",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_14",
        "Type": "Negative",
        "Expected_Result": "Verify Edit Subscription Plan fails gracefully when mandatory fields are removed during update.",
        "Description": "Verify Edit Subscription Plan fails gracefully when mandatory fields are removed during update.",
        "Plan_Name": "EditMandatoryRemoved",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    },
    {
        "TC_ID": "TC_SP_NEG_15",
        "Type": "Negative",
        "Expected_Result": "Verify user cannot access invalid or deleted subscription plan detail page directly via URL.",
        "Description": "Verify user cannot access invalid or deleted subscription plan detail page directly via URL.",
        "Plan_Name": "DeletedDirectURL",
        "Scope": "CUSTOMER",
        "Org_Access": "GLOBAL",
        "Payment_Type": "POST-PAID",
        "Tax_Code": "TAX_VALIDATION_806531",
        "Charge_Code": "CHG_123",
        "Currency": "USD",
        "Price": "19.99",
        "UOM": "AMOUNT",
        "Base_Qty": "1",
        "Cadence": "MONTHLY",
        "Auto_Renewal": "Yes",
        "Plan_Type": "DURATION",
        "Validity_Days": "30",
        "Feature1": "Feature A",
        "Feature2": "NULL"
    }
];

const headers = [
    "TC_ID",
    "Type",
    "Expected_Result",
    "Description",
    "Plan_Name",
    "Scope",
    "Org_Access",
    "Payment_Type",
    "Tax_Code",
    "Charge_Code",
    "Currency",
    "Price",
    "UOM",
    "Base_Qty",
    "Cadence",
    "Auto_Renewal",
    "Plan_Type",
    "Validity_Days",
    "Feature1",
    "Feature2"
];

const wsData = [
    headers,
    ...rows.map((r) => headers.map((h) => r[h] || "")),
];

try {
    const wb = XLSX.readFile(FILE);
    const ws = XLSX.utils.aoa_to_sheet(wsData);

    if (wb.SheetNames.includes(SHEET_NAME)) {
        const idx = wb.SheetNames.indexOf(SHEET_NAME);
        wb.SheetNames.splice(idx, 1);
        delete wb.Sheets[SHEET_NAME];
        console.log(`Removed existing sheet: "${SHEET_NAME}"`);
    }

    XLSX.utils.book_append_sheet(wb, ws, SHEET_NAME);
    XLSX.writeFile(wb, FILE);
    console.log(`Successfully updated ${rows.length} rows in '${SHEET_NAME}' sheet in ${FILE}`);
} catch (err) {
    console.error("Failed to update testData.xlsx:", err.message);
    process.exit(1);
}
